name: Testes de API com Postman + Allure (GitHub Pages)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  testes-postman:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar Newman + Allure
        run: |
          npm install -g newman newman-reporter-allure allure-commandline --save-dev

      - name: Executar Collection Postman
        run: |
          newman run postman/collection.json \
          -e postman/environment.json \
          -r cli,allure \
          --reporter-allure-export allure-results

      - name: Gerar Relatório Allure
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Publicar no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report

